version: '3'
services:
    mysql:
        image: 'mysql:8.0.30'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'Password1!'
            MYSQL_ROOT_HOST: "localhost"
            MYSQL_DATABASE: 'auth_test'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'Password1!'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './database/mysql:/var/lib/mysql'
        networks:
            - mysql-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

networks:
    mysql-network:
        driver: bridge